# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a28f43cbf952bc98d2268ec624a6bf5b52bed9c950081f73d9780def59eab9e2be729c29f0ecc141000f64dd16707f9773411274111f9540c61a0b225862a5a

test:
  secret_key_base: edab2a8712f05b7abe68265f0e6a54b9a065aca3656754a0ca912ac5624e2a204e88bb4d0e03323ff3942c4d3fa09a4a99feae6a2b5a274be5cb9a8e788b8e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
